-- MySQL Script generated by MySQL Workbench
-- 05/12/16 14:39:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aeu-lamp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aeu-lamp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aeu-lamp` DEFAULT CHARACTER SET utf8 ;
USE `aeu-lamp` ;

-- -----------------------------------------------------
-- Table `aeu-lamp`.`tbl_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeu-lamp`.`tbl_users` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `uname` VARCHAR(45) NULL,
  `uauthename` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aeu-lamp`.`tbl_floors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeu-lamp`.`tbl_floors` (
  `fid` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(100) NULL,
  PRIMARY KEY (`fid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aeu-lamp`.`tbl_rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeu-lamp`.`tbl_rooms` (
  `rid` INT NOT NULL AUTO_INCREMENT,
  `rname` VARCHAR(400) NULL,
  `fid` INT NOT NULL,
  PRIMARY KEY (`rid`),
  INDEX `fk_tbl_rooms_tbl_floors_idx` (`fid` ASC),
  CONSTRAINT `fk_tbl_rooms_tbl_floors`
    FOREIGN KEY (`fid`)
    REFERENCES `aeu-lamp`.`tbl_floors` (`fid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aeu-lamp`.`tbl_equipments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeu-lamp`.`tbl_equipments` (
  `eid` INT NOT NULL AUTO_INCREMENT,
  `etype` INT NULL,
  `ename` VARCHAR(100) NULL,
  `estatus` INT NULL,
  `rid` INT NOT NULL,
  PRIMARY KEY (`eid`),
  INDEX `fk_tbl_equipments_tbl_rooms1_idx` (`rid` ASC),
  CONSTRAINT `fk_tbl_equipments_tbl_rooms1`
    FOREIGN KEY (`rid`)
    REFERENCES `aeu-lamp`.`tbl_rooms` (`rid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
